### ISSUE TITLE
Installation via pip without prompt

### ISSUE THREAD

**Issue by kravciuk** [Falldog/pyconcrete#21]
When I install via pip - no promt or waiting for passphraze. 

`pip install pyconcrete
Collecting pyconcrete
Installing collected packages: pyconcrete
Successfully installed pyconcrete-0.11.3`

**Comment by Falldog** [comment]
@kravciuk this is known issue, I had list on README
I had investigated it a while ago.
It's hard to display prompt when install by pip, pip process pyconcrete setup.py via subprocess and force redirect stdout to /dev/null, I think it's not easy issue for now.

**Comment by kravciuk** [comment]
If I undestand correctly, when installing using pip, I must get waiting input for password. 
But when I install using "pip install pyconcrete" command, the installation is processed like other packets. I don't get any feature to input password. 

Maybe it is possible to change password after installation ?

**Comment by Falldog** [comment]
Did you install pyconcrete on the same environment?
I had just test it on ubuntu, and only first time will wait user to input passphrase, I am not sure why non-first time install didn't wait user to input passphrase. Maybe pip do some cache, need to trace pip source code to check the root cause.

Currently, allow user input passphrase when installation to make sure everyone will compile the different `pyconcrete.so` with a different passphrase to make sure basic security. If we want to change password after installation, we could not put passphrase into `pyconcrete.so`, need to store the passphrase into some file and read it every time, and it will more easy to be hack the encrypted passphrase.

**Comment by kravciuk** [comment]
Yes, 100% clean installation on clean CentOS VPS (3 different VPS) in virtualenv environment. 
OS: CentOS 7
virtualenv==15.1.0
pip==9.0.1

**Comment by web-maker** [comment]
Hi guys. I have same problem. After installation via pip there is no way to specify passphrase. To specify passphrase we must clone project and install pyconcrete from source. Or use default passphrase. But with default passphrase it's easy to hack.
Ubuntu 16.04
Python 3.6

**Comment by Falldog** [comment]
It should be fix at #92
